services:
  - type: web
    name: chatapp-frontend
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: chatapp-backend
          property: url
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: chatapp-backend
          property: url
  - type: web
    name: chatapp-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_DB
        fromSecret: MONGO_DB_URL
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: CLOUDINARY_CLOUD_NAME
        fromSecret: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        fromSecret: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        fromSecret: CLOUDINARY_API_SECRET
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: chatapp-frontend
          property: url
      - key: NODE_ENV
        value: production
