services:
  - type: web
    name: chatapp-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_DB
        fromSecret: MONGO_DB_URL
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: CLOUDINARY_CLOUD_NAME
        fromSecret: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        fromSecret: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        fromSecret: CLOUDINARY_API_SECRET
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://justchat-d566.onrender.com
